name: Echo Workflow for Specific Folders

on:
  push:
    paths:
      - 'app/**'      # Trigger for changes in the 'app' folder
      - 'client/**'   # Trigger for changes in the 'client' folder
  pull_request:
    paths:
      - 'app/**'      # Trigger for pull requests affecting the 'app' folder
      - 'client/**'   # Trigger for pull requests affecting the 'client' folder

jobs:
  echo-message:
    runs-on: ubuntu-latest   # Runs on the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # Checkout the code of the repository
      
      - name: Echo a message for app folder changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^app/'; then
            echo "Changes detected in the 'app' folder!"
          fi

      - name: Echo a message for client folder changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^client/'; then
            echo "Changes detected in the 'client' folder!"
          fi
